avatar:
  enable: true
  url: /images/avatar.jpg
  rounded: true
  opacity: 1
  mickey_mouse: false
  status:
    enable: true
    emoji: ğŸ˜­
    message: =.=

favicon: /favicon.ico

social:
  - name: GitHub
    link: https://github.com/MTChaoyi
    icon: icon-github-line
    color: "#181717"
  - name: E-Mail
    link: mailto:MTChaoyi@outlook.com
    icon: icon-mail-line
    color: "#8E71C1"
  - name: å“”å“©å“”å“©åŠ¨ç”»
    link: https://space.bilibili.com/487332642
    icon: icon-bilibili-line
    color: "#FF8EB3"
  - name: Telegram
    link: https://t.me/MTChaoyi
    icon: icon-telegram-line
    color: "#0088CC"
  # RSS npm install hexo-generator-feed --save
  - name: RSS
    link: /atom.xml # config.feed.path
    icon: ri:rss-line
    color: orange

banner:
  enable: true
  title: æ¢¦å¤©çš„å°ç«™
  border: true
  cloud:
    enable: true
    color: "white"
  go_down:
    enable: true
    icon: icon-arrow-down-s-line

# å¯é€‰ light | dark | auto | time
mode: auto

bg_image:
  enable: true
  url: https://cdn.jsdelivr.net/gh/MTChaoyi/Blog-Hexo@main/source/images/background.jpg
  # dark:
  # blur: 30px # è®¾ç½®èƒŒæ™¯æ¨¡ç³Šç¨‹åº¦
  opacity: 0.8

search:
  modal: true
  bg_image: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-2.jpg
  # dark_bg_image: xxx
  # placeholder:

# éšæœºå¤šè¾¹å½¢èƒŒæ™¯
trianglify:
  enable: false
  cellSize: 75
  width: 800
  height: 600
  palette: '["YlGnBu", "GnBu", "Purples", "Blues"]'
  opacity: 0.5

# ç‚¹å‡»æ–‡ç« å›¾ç‰‡ï¼Œæ”¾å¤§é¢„è§ˆã€‚
medium_zoom: true


# ä¾§è¾¹æ 

# èƒŒæ™¯ä¸æ ‡ç­¾
sidebar:
  bg_image: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-1.jpg
  bg_position: bottom 3rem center
  tagcloud:
    enable: false
    amount: 20

menu:
  home:
    path: /
    icon: icon-home-4-line
  list:
    - type: archives
      path: /archives/
      icon: icon-archive-line
    - type: categories
      path: /categories/
      icon: icon-folder-2-line
    - type: tags
      path: /tags/
      icon: icon-price-tag-3-line
    # - path: https://www.yunyoujun.cn
    #   icon: icon-cloud-line
    #   count: ä½ çŒœ
  custom:
    title: å¯¼èˆª
    path: https://MTChaoyi.top/Navigation
    icon: icon-settings-line

pages:

# æ–‡ç« 
# å†…å®¹å¡ç‰‡
post_card:
  opacity: 0.8

post_meta:
  item_text: false
  created_at: false
  updated_at: true
  categories: true
  tags: true

toc:
  list_number: false
  max_depth: 6
  min_depth: 1
  placeholder: å¾ˆé—æ†¾ï¼Œå’±æ²¡å†™å•¥ç›®å½•
  collapse: false

# ç¼–è¾‘é“¾æ¥
post_edit:
  enable: true
  url: https://github.com/MTChaoyi/Blog-Hexo/tree/main/source/

codeblock:
  copy_btn: true

creative_commons:
  license: by-nc-sa
  post: true
  language: deed.zh
  clipboard: false

lazyload:
  enable: true

footer:
  since: 2022
  powered:
    enable: true
  live_time:
    enable: false
    prefix: æœ¬åšå®¢å·²èŒèŒå“’åœ°è¿è¡Œ
    suffix: (â—'â—¡'â—)
    start_time: "2022-03-16T00:00:00"

# é»˜å“€
mourn:
  enable: true
  days:
    - "4-4"

say:
  enable: true
  api: https://cdn.jsdelivr.net/gh/ElpsyCN/say@gh-pages/sentences.json
  # https://developer.hitokoto.cn/sentence/
  hitokoto:
    enable: true
    api: https://v1.hitokoto.cn

engine_search:
  enable: false

# search
# https://github.com/wzpan/hexo-generator-search
local_search:
  enable: true

busuanzi:
  enable: false
  site_uv: true
  site_uv_icon: ri:user-line
  site_pv: true
  site_pv_icon: ri:eye-line
  page_pv: true
  page_pv_icon: ri:eye-line

# å­—æ•°ç»Ÿè®¡ å®‰è£… hexo-wordcount
wordcount:
  enable: true
  count: true
  time: true

# å½©è‰²è¯äº‘
wordcloud:
  enable: true

custom:
  style: source/_data/style/*

cdn:
  js:
    async:
      # é»˜è®¤å¼•å…¥çš„å›¾æ ‡èµ„æºï¼Œä½¿ç”¨ iconfont
      iconfont: //at.alicdn.com/t/font_1140697_dxory92pb0h.js